# Generated by Django 3.1.3 on 2021-06-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follows_likes_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='active',
            field=models.BooleanField(),
        ),
    ]
