# Generated by Django 3.1.3 on 2021-06-02 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210602_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follows',
            name='active',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
        migrations.AddField(
            model_name='follows',
            name='active_bool',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='edit_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='edit_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='edit_datetime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='edit_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.date(2021, 6, 2)),
        ),
        migrations.AddField(
            model_name='post',
            name='post_datetime',
            field=models.DateTimeField(default='2021-06-02 18:42:16'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.TimeField(default='18:42:16'),
        ),
    ]
