# Generated by Django 3.1.3 on 2021-06-02 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210602_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='edit_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='edit_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_time',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 18, 54, 32, 36430, tzinfo=utc)),
        ),
    ]
