# Generated by Django 3.1.3 on 2021-06-02 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210602_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
