# Generated by Django 3.1.3 on 2021-06-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210602_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edit_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
