# Generated by Django 3.1.3 on 2021-06-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210603_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='active_bool',
            field=models.BooleanField(default=True),
        ),
    ]
